title: Ebotian's Blog
author: Ebotian
email: yiboxiaotian@nuaa.edu.cn
description: > # this means to ignore newlines until "show_exerpts:"
  personal blog of GitHub User Ebotian/Nicolette86132/AsilenA123
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
remote_theme: samarsault/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 易博天的个人博客
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: AsilenA123
    github: Ebotian
    #linkedIn: in/thelehhman
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
